### ISSUE TITLE
Handle Focusin and focusout specila event.

### ISSUE THREAD

**Issue by jDramaix** [ArcBees/gwtquery#11]
JQuery supports special events focusin and focusout but gwtquery not yet.

Please add support for these event in bind/unbind methods and live/delegate methods.

**Comment by jDramaix** [comment]
It's not implemented yet. Firefox doesn't support these events and we did nothing in GQuery for adding support to these events

**Comment by manolo** [comment]
I dont know if there is many people interested on fixing this in FF with gquery. 
I think it does not worth to make the effort and maintain the code here, so I vote not to resolve this issue and close as 'wont fix'

**Comment by jDramaix** [comment]
I'm fine with closing is as "on't fix" I would like to avoid that people think it's fixed and supported by GQuery
