### ISSUE TITLE
latest snapshot has ios drag bug

### ISSUE THREAD

**Issue by biancashouse** [ArcBees/gwtquery#337]
When I use gwtquery 1.4.3-SNAPSHOT, my app does not drag when used on an old ipad.

In the console you just see the message "RETTT", which I assume is generated on the drag event.

When I revert to gwtquery-1.4.3-20141231.143602-16.jar, it works.

**Comment by manolo** [comment]
What are you using for DnD, gquery DnD plugins? 
To be exact, does it only happen with iOS, which version of iOS?
Could you post a little bit of the code failing?

**Comment by biancashouse** [comment]
OK, apologies for being vague.
In order to invoke the issue, in my pom I specify:

gwtquery 1.4.3-SNAPSHOT
enhance-plugin 1.0.5

The issue is that when I drag an element, in IOS I just see RETTT in the console many times.
This console message is generated in com.google.gwt.query.client.plugins.events.EventsListener, in it's onBrowserEvent() method.

I tried it on my Nexus 7 and no issue, but on my old ipad IOS 8.1.1, the drag doesn't work, and when I attach the ipad to my IMac, I see the RETTT in the console.

*** What is quite interesting is that this issue even shows up when I test in SDM mode in Chrome with Touch emulation enabled. When I select Nexus 7 emulation, no problem, but if I select iphone6 or ipad 1/2, I have the issue.

So is it related to my .gwt.xml ?

Here's my gwt.xml:

<?xml version="1.0" encoding="UTF-8"?>
<module rename-to="GWT_Module">

	<inherits name='com.google.gwt.user.User' />

	<inherits name="com.google.gwt.resources.Resources" />
	<inherits name="com.google.gwt.i18n.I18N" />

	<inherits name='com.google.web.bindery.event.EventBinder' />
	<inherits name='com.google.gwt.json.JSON' />

	<inherits name="com.google.gwt.query.Query" />
	<inherits name='gwtquery.plugins.draggable.Draggable' />
	<inherits name='gwtquery.plugins.droppable.Droppable' />

	
	<inherits name="org.gwtbootstrap3.GwtBootstrap3" />
	<inherits name="org.gwtbootstrap3.extras.slider.Slider" />
	<inherits name="org.gwtbootstrap3.extras.bootbox.Bootbox" />
	<inherits name="org.gwtbootstrap3.extras.growl.Growl" />
	
	<inherits name="org.gwtbootstrap3.extras.summernote.Summernote" />
	<inherits name="org.gwtbootstrap3.extras.card.Card" />

	

	
	<inherits name="com.github.nmorel.gwtjackson.GwtJackson" />
	

	
	<inherits name="com.google.gwt.activity.Activity" />
	<inherits name="com.google.gwt.place.Place" />
	

	<define-property name="gwt.logging.firebugHandler" values="ENABLED, DISABLED" />
	<define-property name="gwt.logging.popupHandler" values="ENABLED, DISABLED" />

	<inherits name="com.googlecode.mgwt.MGWT" />
	<inherits name="com.googlecode.gwtphonegap.PhoneGap" />
	<inherits name="com.googlecode.mgwt.linker.Linker" />


	
	<replace-with class="com.bh.gwt.module.client.common.factory.ClientFactoryImpl">
		<when-type-is class="com.bh.gwt.module.client.common.factory.ClientFactory" />
	</replace-with>
	


	
	
	
	
	<replace-with class="com.google.gwt.canvas.client.Canvas.CanvasElementSupportDetectedMaybe">
		<when-type-is class="com.google.gwt.canvas.client.Canvas.CanvasElementSupportDetector" />
	</replace-with>

	<inherits name="com.google.web.bindery.autobean.AutoBean" />

	
	<inherits name="com.google.api.gwt.oauth2.OAuth2" />


	<inherits name="com.google.gwt.xml.XML" />

	
	

	<replace-with class="com.bh.gwt.module.client.app.AppActivityMapper">
		<when-type-is class="com.bh.gwt.module.client.common.app.i.I_NSActivityMapper" />
	</replace-with>
	<replace-with class="com.bh.gwt.module.client.app.AppAnimationMapper">
		<when-type-is class="com.bh.gwt.module.client.common.app.i.I_AnimationMapper" />
	</replace-with>

	
	<inherits name="com.google.gwt.logging.Logging" />
	<set-property name="gwt.logging.logLevel" value="INFO" />
	<set-property name="gwt.logging.enabled" value="TRUE" />
	<set-property name="gwt.logging.simpleRemoteHandler" value="DISABLED" />
	<set-property name="gwt.logging.consoleHandler" value="ENABLED" />
	<set-property name="gwt.logging.developmentModeHandler" value="ENABLED" />
	<set-property name="gwt.logging.systemHandler" value="ENABLED" />
	<set-property name="gwt.logging.firebugHandler" value="ENABLED" />
	

	
	
	
	

	

	

	

	

	
	<add-linker name="xsiframe" />
	
	


	

	<set-configuration-property name="devModeUrlWhitelistRegexp" value="http://(localhost|127\.0\.0\.1)(:\d+)?/.*" />

	<set-property name="compiler.stackMode" value="emulated" />
	<set-property name="compiler.useSourceMaps" value="true" />
	<set-configuration-property name="compiler.emulatedStack.recordLineNumbers" value="true" />
	<set-configuration-property name="compiler.emulatedStack.recordFileNames" value="true" />

	

	

	
	<set-configuration-property name="mgwt.css" value="pretty" />

	
	


	
	
	
	
	
	
	
	

	
	<entry-point class='com.bh.gwt.module.client.app.AppEntryPoint' />
	

	
	<source path='client' />
	<source path='shared' />
	<source path='res' />

</module>

**Comment by biancashouse** [comment]
I have posted a comment with the issue, which pinpoints the new version of
onBrowserEvent() in EventsListener.

Also, I haven't seen this gwt compile warning until lately:

    Computing all possible rebind results for
'gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl'

     [exec] [INFO]       Rebinding
gwtquery.plugins.draggable.client.impl.DraggableHandlerImpl

     [exec] [INFO]          Could not find an exact match rule. Using
'closest' rule <replace-with
class='gwtquery.plugins.draggable.client.impl.DraggableHandlerImplIE8'/>
based on fall back values. You may need to implement a specific binding in
case the fall back behavior does not replace the missing binding

On Thu, Jan 15, 2015 at 5:27 PM, Manuel Carrasco Moñino <
notifications@github.com> wrote:

> What are you using for DnD, gquery DnD plugins?
> To be exact, does it only happen with iOS, which version of iOS?
> Could you post a little bit of the code failing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArcBees/gwtquery/issues/337#issuecomment-70045123>.
>



-- 
Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by biancashouse** [comment]
BTW - the above .gwt.xml generates 18 permutations during gwt compilation

**Comment by manolo** [comment]
The message "RETTT" has been eliminated in 1.4.4-SNAPSHOT.
Also some fixes which I don't know if they are fixing the DnD issues, could you test with the new version?

**Comment by manolo** [comment]
@biancashouse Have you tested the snapshot ?

**Comment by biancashouse** [comment]
I'm doing a high pressure job until Friday.
Once that's out of the way, I will definitely be looking at the latest
snapshot to see what's going wrong for me. Apologies for the delay.

Without going into any detail, I did note that the snapshot seemed to be a
packaging of what I already have been using for a long time: the
enhance-plugin 1.0.5, which includes draggable 1.0.4 and droppable 1.0.8.

If the latest snapshot is still those same version, I don't need to change
my pom, right ?

Or is there later versions of that code in 1.4.4 ?

Ian

On Wed, Feb 25, 2015 at 8:24 PM, Manuel Carrasco Moñino <
notifications@github.com> wrote:

> @biancashouse <https://github.com/biancashouse> Have you tested the
> snapshot ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArcBees/gwtquery/issues/337#issuecomment-75929468>.
>



-- 
Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by biancashouse** [comment]
Manuel,

I'd like to bring my projects up to the latest versions of gquery and
draggable and droppable.

My understanding is that I should now be using 1.4.4-SNAPSHOT for gquery,
and 2.0-SNAPSHOT for the droppable (and draggable).

When I try to use this latest version of droppable I get what look like
randon compile errors. See https://github.com/ArcBees/gwtquery/issues/344.

I have been using the enhance plugin for a long time to do dnd, but would
like to be using the latest code so that I can contribute to the testing
and feeding back of issues.

So for now, I have reverted back to enhance 1.0.5, and will be retesting my
app on ipad and nexus 7.

On Wed, Feb 25, 2015 at 9:33 PM, Ian White <ian@biancashouse.com> wrote:

> I'm doing a high pressure job until Friday.
> Once that's out of the way, I will definitely be looking at the latest
> snapshot to see what's going wrong for me. Apologies for the delay.
>
> Without going into any detail, I did note that the snapshot seemed to be a
> packaging of what I already have been using for a long time: the
> enhance-plugin 1.0.5, which includes draggable 1.0.4 and droppable 1.0.8.
>
> If the latest snapshot is still those same version, I don't need to change
> my pom, right ?
>
> Or is there later versions of that code in 1.4.4 ?
>
> Ian
>
> On Wed, Feb 25, 2015 at 8:24 PM, Manuel Carrasco Moñino <
> notifications@github.com> wrote:
>
>> @biancashouse <https://github.com/biancashouse> Have you tested the
>> snapshot ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ArcBees/gwtquery/issues/337#issuecomment-75929468>.
>>
>
>
>
> --
> Ian White
> h: +61 2 9948 9739
> m: +61 404 950 122
> skype (home): biancashouse
>



-- 
Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse

**Comment by biancashouse** [comment]
ok, I find that the problem I have been having with scrolling a flowpanel of draggables has been solved - I was using ScrollPanel, when I really meant to be using CustomScrollPanel.

So I will close this issue. While I'm very happy to resolve this issue, I still have never managed to get a build compiled using any combination of these artifacts later than these versions: 

    gwt-query-1.4.3-SNAPSHOT
    enhance-plugin 1.0.5, which includes draggable 1.0.4 and droppable 1.0.8

I'm happy to wait for new 2.0 versions which might coincide with gwt 2.8 ?

**Comment by christiangoudreau** [comment]
@meriouma @jDramaix any ideas?

**Comment by biancashouse** [comment]
When I tried using gquery 2.0.0-SNAPSHOT, I got:

    Missing artifact com.google.gwt:gwt-elemental:jar:2.8.0-MCM

and so I added an exclusion to make it use the 2.7.0 elemental, I get these
compile errors:

 <anonymous
au.com.mobilett.gwt.gamehub.client.app.mobilett.TrainingProgramDemo$3> is
not abstract and does not override abstract method call(Object,Object) in
IsReturnFunction2

The cause of such compile errors appears to be when I use the GQuery f
function with a single or no arg ?


Promise loggingIn = GQuery.when(GQuery.ajax(loginSettings));


loggingIn.done(new Function() {

  public void f() {


loggingIn.fail(new Function() {

public void f() {


$("button.post-q-btn").click(new Function() {

public boolean f(Event e) {

bubblePlayer.stop();

return true;

}

   });


and here's what my maven deps look like:

/Users/ianw/.m2/repository/com/googlecode/gwtquery/gwtquery/2.0.0-SNAPSHOT/gwtquery-2.0.0-SNAPSHOT.jar

/Users/ianw/.m2/repository/com/googlecode/gwtquery/plugins/enhance-plugin/1.0.5/enhance-plugin-1.0.5.jar

/Users/ianw/.m2/repository/com/google/gwt/gwt-elemental/2.7.0/gwt-elemental-2.7.0.jar

/Users/ianw/.m2/repository/org/gwtbootstrap3/gwtbootstrap3/1.0-SNAPSHOT/gwtbootstrap3-1.0-SNAPSHOT.jar

/Users/ianw/.m2/repository/org/gwtbootstrap3/gwtbootstrap3-extras/1.0-SNAPSHOT/gwtbootstrap3-extras-1.0-SNAPSHOT.jar

/Users/ianw/.m2/repository/junit/junit/4.10/junit-4.10.jar

/Users/ianw/.m2/repository/org/hamcrest/hamcrest-core/1.1/hamcrest-core-1.1.jar

/Users/ianw/.m2/repository/com/google/gwt/gwt-user/2.7.0/gwt-user-2.7.0.jar

/Users/ianw/.m2/repository/com/google/gwt/eventbinder/eventbinder/1.1.0/eventbinder-1.1.0.jar

/Users/ianw/.m2/repository/com/googlecode/gwtphonegap/gwtphonegap/
3.5.0.0/gwtphonegap-3.5.0.0.jar

/Users/ianw/.m2/repository/commons-io/commons-io/2.0.1/commons-io-2.0.1.jar

/Users/ianw/.m2/repository/com/googlecode/mgwt/mgwt/2.0.0/mgwt-2.0.0.jar

/Users/ianw/.m2/repository/com/github/nmorel/gwtjackson/gwt-jackson/0.2.1/gwt-jackson-0.2.1.jar

/Users/ianw/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar

/Users/ianw/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0-sources.jar

/Users/ianw/.m2/repository/org/mockito/mockito-all/1.9.0/mockito-all-1.9.0.jar

/Users/ianw/.m2/repository/javax/validation/validation-api/
1.0.0.GA/validation-api-1.0.0.GA.jar

/Users/ianw/.m2/repository/javax/validation/validation-api/
1.0.0.GA/validation-api-1.0.0.GA-sources.jar

On Tue, Mar 3, 2015 at 12:32 AM, christiangoudreau <notifications@github.com
> wrote:

> @meriouma <https://github.com/meriouma> @jDramaix
> <https://github.com/jDramaix> any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArcBees/gwtquery/issues/337#issuecomment-76711588>.
>



-- 
Ian White
h: +61 2 9948 9739
m: +61 404 950 122
skype (home): biancashouse
