### ISSUE TITLE
GWT-2.8-SNAPSHOT + SDM : The method $(Element) is ambiguous for the type GQuery 

### ISSUE THREAD

**Issue by nmarchais** [ArcBees/gwtquery#342]
I am using GQuery 1.4.3 with GWT 2.8-SNAPSHOT and everything works fine when I compile with maven.

When I launch SDM from an eclipse launcher i have this error :

 Tracing compile failure path for type 'com.google.gwt.query.client.GQuery'
            [ERROR] Errors in 'com/google/gwt/query/client/GQuery.java'
               [ERROR] Line 226: The method $(Element) is ambiguous for the type GQuery
            [ERROR] Errors in 'com/google/gwt/query/client/LazyGQuery.java'
               [ERROR] com.google.gwt.query.client.GQuery.Offset cannot be resolved to a type
            [ERROR] Errors in 'com/google/gwt/query/client/plugins/Effects.java'
               [ERROR] com.google.gwt.query.client.GQuery cannot be resolved to a type
            [ERROR] Errors in 'com/google/gwt/query/client/plugins/Plugin.java'
               [ERROR] com.google.gwt.query.client.GQuery cannot be resolved to a type
            [ERROR] Errors in 'com/google/gwt/query/client/plugins/Events.java'
               [ERROR] com.google.gwt.query.client.GQuery cannot be resolved to a type
            [ERROR] Errors in 'com/google/gwt/query/client/impl/AttributeImpl.java'
               [ERROR] com.google.gwt.query.client.GQuery cannot be resolved to a type
            [ERROR] Errors in 'com/google/gwt/query/client/plugins/Widgets.java'
               [ERROR] com.google.gwt.query.client.GQuery cannot be resolved to a type
            [ERROR] Errors in 'com/google/gwt/query/client/plugins/QueuePlugin.java'
               [ERROR] com.google.gwt.query.client.GQuery cannot be resolved to a type

Also a lot of warning are written to the console. Here is an example of warning : 

Computing all possible rebind results for 'com.aadprox.client.core.ui.drive.FileBrowserView.FileBrowserViewUiBinder'
            Rebinding com.aadprox.client.core.ui.drive.FileBrowserView.FileBrowserViewUiBinder
               Checking rule <replace-with class='com.google.gwt.query.client.plugins.effects.TransitionsAnimation.TransitionsClipAnimation'/>
                  [WARN] Unknown type 'com.google.gwt.query.client.plugins.Effects.GQAnimation' specified in deferred binding rule
               Checking rule <replace-with class='com.google.gwt.query.client.plugins.effects.ClipAnimation'/>
                  [WARN] Unknown type 'com.google.gwt.query.client.plugins.Effects.GQAnimation' specified in deferred binding rule

Do you think it's a configuration problem on my side or is it a bug ?

**Comment by nmarchais** [comment]
On more information :
When i remove GQuery lib from my project SDM works perfectly !

**Comment by nmarchais** [comment]
I succeed to launch SDM with GQuery thank to maven gwt plugin --> gwt:run-codeserver.
It's my eclipse launch configuration which is probably wrong.
Sorry for disturbing you...

**Comment by thebeeber** [comment]
I am getting the same message.  Just upgraded java version to 1.8, switched to gwtquery 1.4.3, and I get this when I compile using maven:

Checking rule <replace-with class='com.google.gwt.query.client.plugins.effects.TransitionsAnimation.TransitionsClipAnimation'/>
[INFO]             [WARN] Unknown type 'com.google.gwt.query.client.plugins.Effects.GQAnimation' specified in deferred binding rule
[INFO]          Checking rule <replace-with class='com.google.gwt.query.client.plugins.effects.ClipAnimation'/>
[INFO]             [WARN] Unknown type 'com.google.gwt.query.client.plugins.Effects.GQAnimation' specified in deferred binding rule

I've checked my dependencies, and everything looks right.  Any ideas? Could really use some help,

**Comment by meriouma** [comment]
GWT-2.8 and java 8 requires GQuery 1.4.4-SNAPSHOT

**Comment by thebeeber** [comment]
Thanks so much for the quick response!

**Comment by olafleur** [comment]
@meriouma : would it be worthwhile to make a release 1.4.4 with these changes?

**Comment by meriouma** [comment]
I think we could release just after GWT 2.8 is released

**Comment by ibaca** [comment]
You can release 1.4.4-beta1 :wink:

**Comment by natros** [comment]
👍

**Comment by michael-newsrx** [comment]
Would be nice for a beta snapshot to be released that works with gwt 2.8 beta1

**Comment by olafleur** [comment]
We just released GWTQuery version 1.5 beta 1 . Thanks @meriouma !

**Comment by silentsnooc** [comment]
Is recommended to go with 1.5 beta 1 instead of 1.4.4-beta1 ?

**Comment by olafleur** [comment]
The recommended version to go with GWT 2.8 beta1 is 1.5beta1
