### ISSUE TITLE
Remove these changes, they are unrelated with the commit feature

### ISSUE THREAD

**Issue by manolo** [ArcBees/gwtquery#353]
|commit|file reference|pull request|   |
|------|--------------|------------|---|
|37406cfd4dc20f27fe53af3ae8c2cc98bf6ef3aa|[gwtquery-core/src/test/java/com/google/gwt/query/client/GQueryJsInteropTestGwt.java#L41](https://github.com/ArcBees/gwtquery/blob/37406cfd4dc20f27fe53af3ae8c2cc98bf6ef3aa/gwtquery-core/src/test/java/com/google/gwt/query/client/GQueryJsInteropTestGwt.java#L41)| #351 |[![#351](http://app.review.ninja/assets/images/icon-alt-36.png)](http://app.review.ninja/ArcBees/gwtquery/pull/351)|

**Comment by jDramaix** [comment]
When does this change have been merged ?

**Comment by manolo** [comment]
It seems nothing was merged in master. I was experimenting with review ninja, and tried to make a comment to #351. It seems that review ninja opens a new issue when adding a comment to the code
