### ISSUE TITLE
main gwtquery fork

### ISSUE THREAD

**Issue by heyarny** [ArcBees/gwtquery#365]
Hello,

what happened to the main fork? There is no issue tab activated. No updates for some time.
Is gwtquery still maintained or slowly dying?

**Comment by olafleur** [comment]
Hi @heyarny !

In fact, the main fork for GWTQuery is now this one.

The project was formerly maintained by individuals as volunteer work, but the company Arcbees (for which I work) announced official support last year here : http://blog.arcbees.com/2014/10/28/a-guaranteed-future-for-gquery/
So the project was then moved to this repo.

So, as you did, feel free to open your issues or submit your pull requests in this repo.

Closing this issue. Don't hesitate if you have other questions. It will be a pleasure to help !
