### ISSUE TITLE
Are there any current SNAPSHOT builds?

### ISSUE THREAD

**Issue by dodgex** [ArcBees/gwtquery#371]
I recently upgraded one of our projects to use GWT 2.8-beta1 and gwtquery 1.4.4-SNAPSHOT (as there where errors with 1.4.3 `The method $(Element) is ambiguous for the type GQuery` fixed in https://github.com/ArcBees/gwtquery/commit/3174d5ba98027c8d106d252747f5c1e1205f8fe2)

now i have the problem, that i want to add a change handler to a `SelectElement` but due to another issue in gwtquery the `SelectElement` is handled as `NodeList` and with `$(selectElement)` i do not get a GQuery instance for `selectElement` but for its child `<option>` elements. the issue seems to be fixed in https://github.com/ArcBees/gwtquery/commit/24542fc0b901d7a4cf7fadbc78022616eb0b0c6d with follow up fixes in https://github.com/ArcBees/gwtquery/commit/081412bfbae1dd80979db4695e1f36aa723fdfea and https://github.com/ArcBees/gwtquery/commit/797ce9bd21faa8c7c9d1fd043aac033a60ade0cc but those changes are not in the current snapshot from https://oss.sonatype.org/content/repositories/snapshots/com/googlecode/gwtquery/gwtquery/

are snapshots on another location now or are there issues with snapshot generation?

thanks in advance :)

**Comment by meriouma** [comment]
Thanks. We'll fix the snapshot generation

**Comment by meriouma** [comment]
New snapshot is up

**Comment by dodgex** [comment]
Thank you very much. I'll test it tomorrow!
