### ISSUE TITLE
Unable to construct a multipart Ajax call - no examples anywhere

### ISSUE THREAD

**Issue by biancashouse** [ArcBees/gwtquery#380]
In order to upload a new file on a Google Drive you have to POST a multipart message with the contents of the file plus metadata that specifies the file name and which folder to place it etc.

Try as I might I cannot find a way to make the correct Ajax() call.

Any guidance would be much appreciated. Thanks.

**Comment by yadavharsh** [comment]
Hi @biancashouse 

Here is an example:
http://gwtquery.github.io/gwt.create-slides/gwtcreate2015/gwtcreate2015.html#32

http://stackoverflow.com/questions/30346031/progress-percentage-from-browser-on-post-multipart-request-gwt
