### ISSUE TITLE
add  GQuery $(SafeHtml hml) method

### ISSUE THREAD

**Issue by jDramaix** [ArcBees/gwtquery#93]
_Original author: julien.d...@gmail.com (November 14, 2010 21:47:20)_

Could be nice to have this method :

/**
- This function accepts a SafeHtml object
  */
  public static GQuery $(SafeHtml html) {
  return innerHtml(html.asString());
  }

_Original issue: http://code.google.com/p/gwtquery/issues/detail?id=61_

**Comment by 0x3333** [comment]
I was going to post a feature request exactly about this report.

Wouldn't it make sense now? SafeHtml is here to stay, all current versions support it.

Give me your thoughts...

Thanks!

**Comment by jDramaix** [comment]
Yep I think it should be nice to have this method now. 

@manolo What do you think ?

@0x3333 Do you think you could propose a PR for that ?

**Comment by 0x3333** [comment]
Yep, sure. Just give me a go/no go.

**Comment by 0x3333** [comment]
I just created the PR anyway...

https://github.com/ArcBees/gwtquery/pull/346

**Comment by jDramaix** [comment]
Thanks for the contribution. The PR has been merged
